# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.1.6
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: monjie12272@gmail.com
author_name: Dowiw
contract_name: decentralized_donating
deployment_language: python
preset_name: starter
project_name: decentralized_donating

