# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.1.1
_src_path: gh:algorandfoundation/algokit-react-frontend-template
author_email: gabrielkuettel@gmail.com
author_name: Gabriel Kuettel
cloud_provider: vercel
preset_name: production
project_name: fractional-realestate-ts-frontend

