# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.6.3
_src_path: gh:algorandfoundation/algokit-python-template
author_email: monjie12272@gmail.com
author_name: Dowiw
contract_name: decentralized_donating
deployment_language: python
preset_name: starter
project_name: decentralized_donating-contracts

