name: Pull Request validation

on: [pull_request]


jobs:
  fractional-realestate-py-contracts-ci:
    name: Run fractional-realestate-py-contracts validation
    uses: ./.github/workflows/fractional-realestate-py-contracts-ci.yaml

  fractional-realestate-py-frontend-ci:
    name: Run fractional-realestate-py-frontend validation
    uses: ./.github/workflows/fractional-realestate-py-frontend-ci.yaml

